### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by talented-full-dev** [talented-full-dev/Go_guessing#16]
Hello.
There are some problems in dev and change branches with coding style.

**Comment by Zanhuesu** [comment]
Okay. 
You are right.
In my opinion, this is not bid deal for us.
So, I will tackle this in a short period.
No worries.

**Comment by supercrytoking** [comment]
Master. You are right!
I will consider these points for your success result.
Thanks.

**Comment by talented-full-dev** [comment]
Hello everyone.
I will keep all your advices.
Thanks.
Hope producing good result.
